openapi: 3.0.0
info:
  title: HDT API Documentation
  description: >-
    API documentation for the HDT system, providing endpoints for model and app
    developers to access virtual twin data.
  version: 1.0.0-oas3
servers:
  - url: http://localhost:5000
    description: Local server for testing
paths:
  /metadata/model_developer_apis:
    get:
      summary: Retrieve metadata for model developer APIs
      description: >-
        Provides details about model developer APIs, including their
        functionality, input requirements, and output structure.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  endpoints:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        url:
                          type: string
                        method:
                          type: string
                        description:
                          type: string
                        expected_input:
                          type: object
                          properties:
                            headers:
                              type: object
                              properties:
                                Authorization:
                                  type: string
                                  example: Bearer <API_KEY>
                        functionality:
                          type: string
                        output:
                          type: object
                          properties:
                            user_id:
                              type: integer
                            data:
                              type: object
                              properties:
                                trivia_results:
                                  type: array
                                  items:
                                    type: string
                                latest_activity_info:
                                  type: string
                            error:
                              type: string
        '500':
          description: Internal server error
  /metadata/app_developer_apis:
    get:
      summary: Retrieve metadata for app developer APIs
      description: >-
        Provides details about app developer APIs, including their
        functionality, input requirements, and output structure.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  endpoints:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        url:
                          type: string
                        method:
                          type: string
                        description:
                          type: string
                        expected_input:
                          type: object
                          properties:
                            query_params:
                              type: object
                              properties:
                                user_id:
                                  type: integer
                            headers:
                              type: object
                              properties:
                                Authorization:
                                  type: string
                                  example: Bearer <API_KEY>
                        functionality:
                          type: string
                        output:
                          type: object
                          properties:
                            user_id:
                              type: integer
                            latest_update:
                              type: string
                            player_types:
                              type: object
                              properties:
                                Socializer:
                                  type: number
                                Competitive:
                                  type: number
                                Explorer:
                                  type: number
                            error:
                              type: string
        '500':
          description: Internal server error
  /get_trivia_data:
    get:
      summary: Retrieve trivia data
      description: Fetch trivia data for virtual twin model training.
      parameters:
        - name: Authorization
          in: header
          description: Bearer token for API authentication.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user_id:
                      type: integer
                    data:
                      type: object
                      properties:
                        trivia_results:
                          type: object
                          additionalProperties:
                            type: object
                            properties:
                              CORRECT:
                                type: integer
                              INCORRECT:
                                type: integer
                        latest_activity_info:
                          type: object
                          properties:
                            id:
                              type: integer
                            timestamp:
                              type: string
                              format: date-time
                    error:
                      type: string
        '403':
          description: Unauthorized access
        '500':
          description: Internal server error
  /get_sugarvita_data:
    get:
      summary: Retrieve SugarVita data
      description: Fetch SugarVita metrics for virtual twin model training.
      parameters:
        - name: Authorization
          in: header
          description: Bearer token for API authentication.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user_id:
                      type: integer
                    data:
                      type: object
                      properties:
                        sugarvita_results:
                          type: object
                          properties:
                            DAYS_PLAYED:
                              type: array
                              items:
                                type: integer
                            GLUCOSE_ACCURACY:
                              type: array
                              items:
                                type: number
                        latest_activity_info:
                          type: object
                          properties:
                            engagement:
                              type: object
                              properties:
                                id:
                                  type: integer
                                timestamp:
                                  type: string
                                  format: date-time
                            playthrough:
                              type: object
                              properties:
                                id:
                                  type: integer
                                timestamp:
                                  type: string
                                  format: date-time
                    error:
                      type: string
        '403':
          description: Unauthorized access
        '500':
          description: Internal server error
  /get_walk_data:
    get:
      summary: Retrieve walk data
      description: Fetch step count and walk-related metrics.
      parameters:
        - name: Authorization
          in: header
          description: Bearer token for API authentication.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user_id:
                      type: integer
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          date:
                            type: string
                            format: date-time
                          distance_meters:
                            type: number
                          duration:
                            type: string
                          kcalories:
                            type: number
                          steps:
                            type: integer
                    error:
                      type: string
        '403':
          description: Unauthorized access
        '500':
          description: Internal server error
  /get_sugarvita_player_types:
    get:
      summary: Retrieve SugarVita player type scores
      description: Get player type labels and scores derived from SugarVita data.
      parameters:
        - name: user_id
          in: query
          description: ID of the user to query
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          description: Bearer token for API authentication.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  latest_update:
                    type: string
                  player_types:
                    type: object
                    properties:
                      Socializer:
                        type: number
                      Competitive:
                        type: number
                      Explorer:
                        type: number
        '403':
          description: Unauthorized access
        '500':
          description: Internal server error
  /get_health_literacy_diabetes:
    get:
      summary: Retrieve diabetes health literacy scores
      description: Get health literacy scores related to diabetes.
      parameters:
        - name: user_id
          in: query
          description: ID of the user to query
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          description: Bearer token for API authentication.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  latest_update:
                    type: string
                  health_literacy_score:
                    type: object
                    properties:
                      name:
                        type: string
                      score:
                        type: number
                      sources:
                        type: object
                        properties:
                          trivia:
                            type: number
                          sugarvita:
                            type: number
        '403':
          description: Unauthorized access
        '500':
          description: Internal server error
